name: live_camera_app2
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  csv: ^5.0.1
  webview_flutter: ^4.4.2
  youtube_player_flutter: ^9.1.1
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_inappwebview: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/japan-livecamera_data.csv